handling errors in various files
bhuvansingla/iitk-coin pull request #21
Opened 2021-10-16 22:03 UTC by erikvegax

#9 

lmk if you guys see anything that needs fixing or changing

2021-10-17 13:53 UTC, 1-Harshit reviewed
error messages can be improved and make sure handlers return `errors.NewHTTPError`

2021-10-17 13:53 UTC, 1-Harshit commented on account/reward.go
> +		return err
Is this `return err` consistent with our `errors.NewHTTPError` ?

2021-10-17 14:44 UTC, bhuvansingla commented on account/reward.go
> +		return err
Yes, return an internal server error.

2021-10-17 14:46 UTC, bhuvansingla commented on auth/login.go
> +		return false, errors.NewHTTPError(nil, http.StatusBadRequest, "error loggin in")
This should be an internal server error, with the default message for internal server error.

2021-10-17 14:52 UTC, bhuvansingla commented on auth/login.go
> +		return false, errors.NewHTTPError(nil, http.StatusBadRequest, "error loggin in")
Here is an example: https://github.com/bhuvansingla/iitk-coin/blob/68efda6cef6e04ae8544d3d438bb07a5a7b92205/handlers/balance.go#L47

2021-10-18 20:40 UTC, erikvega commented
hey guys! how should i know when to return an internal server error vs. a regular error?

2021-10-18 21:11 UTC, erikvegax commented
went through a used internal server error in the files that i was working on. lmk if you guys want me to fix anything else

2021-10-18 21:14 UTC, erikvegax commented
also, i saw some errors where the string was capitalized. i think it's convention to have the sentence all lowercase as suggested by the [golang style guide](https://github.com/golang/go/wiki/CodeReviewComments#error-strings).

2021-10-19 06:05 UTC, 1-Harshit commented
> hey guys! how should i know when to return an internal server error vs. a regular error?  

@erikvega when it is error from our side, computational or accessing database (not returning anything against query is another thing but failing while executing the query is an internal server error) etc...




> also, i saw some errors where the string was capitalized. i think it's convention to have the sentence all lowercase as suggested by the [golang style guide](https://github.com/golang/go/wiki/CodeReviewComments#error-strings).

That's true, if u see them pls fix them or highlight it

2021-10-21 11:46 UTC, bhuvansingla requested changes

2021-10-21 11:46 UTC, bhuvansingla commented on account/user.go
>  func IsAdmin(rollno string) bool {
@erikvega can you also modify this method to check for errors that might get passed on from `GetAccountRoleByRollno` on L91?

2021-10-22 01:42 UTC, erikvegax commented
i went ahead and added the changes that @bhuvansingla requested. i'll let one of you guys handle the conflict because you will know what's best. any other changes?

2021-10-22 06:31 UTC, bhuvansingla approved these changes
LGTM.

2021-10-22 06:33 UTC, merged